#!/usr/bin/env python

import argparse
import importlib
import sandworks
from sandworks.generators import playground
import os

parser = argparse.ArgumentParser(description='Generate some cool spline art')

subparsers = parser.add_subparsers(
    dest='generator',
    title='Generators',
    description='Types of generator subcommands')

playground_parser = subparsers.add_parser('playground')
splines_parser = subparsers.add_parser('splines')
circles_parser = subparsers.add_parser('circles')
grid_parser = subparsers.add_parser('grid')

sub_parsers = [
    playground_parser,
    splines_parser,
    circles_parser,
    grid_parser
]

playground_parser.add_argument(
    '--count',
    default=10000,
    type=int,
    help='number of noise itterations')

splines_parser.add_argument(
    '--count',
    default=10000,
    type=int,
    help='number of noise itterations')

splines_parser.add_argument(
    '--dir',
    default='horizontal',
    type=str,
    choices=('horizontal', 'vertical'),
    help='direction to draw lines')

splines_parser.add_argument(
    '--lines',
    default=50,
    type=int,
    help='number of lines to draw')

splines_parser.add_argument(
    '--save-every',
    default=500,
    type=int,
    help='Number of drawing iterations before writing a frame to PNG')

circles_parser.add_argument(
    '--save-every',
    default=500,
    type=int,
    help='Number of drawing iterations before writing a frame to PNG')

grid_parser.add_argument(
    '--save-every',
    default=500,
    type=int,
    help='Number of drawing iterations before writing a frame to PNG')

for sub_parser in sub_parsers:
    sub_parser.add_argument(
        '--color',
        default='cc0000',
        type=lambda d: d.replace('#', ''),
        help='Color of sand')
    sub_parser.add_argument(
        '--bg-color',
        default='ffffff',
        type=lambda d: d.replace('#', ''),
        help='Color of background')
    sub_parser.add_argument(
        '--width',
        default=1500,
        type=int,
        help='pixel size of width')
    sub_parser.add_argument(
        '--height',
        default=1500,
        type=int,
        help='pixel size of height')
    sub_parser.add_argument(
        '--margin',
        default=100,
        type=int,
        help='Margin around borders of artwork canvas')
    sub_parser.add_argument(
        '--out-dir',
        default='tmp',
        type=str,
        help='directory to output results')
    sub_parser.add_argument(
        '--frame-prefix',
        default='timestamp',
        type=str,
        help='string prefix for frame images')

args = parser.parse_args()
generator_name = "sandworks.generators.{}".format(args.generator)

try:
    os.makedirs(args.out_dir, exist_ok=True)
    generate_function = getattr(importlib.import_module(generator_name), 'generate')
    generate_function(args)
except Exception as e:
    raise e
