#!/usr/bin/env python

import argparse
import importlib
import splineworks
from splineworks.generators import playground

parser = argparse.ArgumentParser(description='Generate some cool spline art')

subparsers = parser.add_subparsers(
    dest='generator',
    title='Generators',
    description='Types of generator subcommands')

playground_parser = subparsers.add_parser('playground')
playground_parser.add_argument(
    '-s', '--size',
    default=1400,
    type=int,
    help='pixel size of width/height')

args = parser.parse_args()

generator_name = "splineworks.generators.{}".format(args.generator)

try:
    Generator = getattr(importlib.import_module(generator_name), 'Generator')
    Generator(args)
except Exception as e:
    raise e
